name: Build Image

on:
 push:
  paths:
    - 'alpine/**'
    - 'debian/**'
    - '.github/workflows/docker_image.yaml'
  pull_request:
    paths:
    - 'alpine/**'
    - 'debian/**'
    - '.github/workflows/docker_image.yaml'
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  "0 6 * * *"
  workflow_dispatch:


env:
  #IMAGE: "docker.io/fjudith/draw.io"
  IMAGE: "docker.io/zhengmz/draw.io"
  VERSION_FILE: "./drawio/VERSION"

jobs:
  image-build:
    name: "Building ${{ matrix.drawio }} base image"
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        drawio:
          - debian
          - alpine
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set ENV variables
        run: |
          echo VERSION=$(curl -s https://raw.githubusercontent.com/jgraph/drawio/master/VERSION | cat) >> $GITHUB_ENV
          echo BUILD_DATE=$(date -u "+%Y-%m-%d %H:%M:%S.%s") >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: >-
            ${{ env.IMAGE }}:${{ env.VERSION }}-${{ matrix.drawio }},
            ${{ env.IMAGE }}:${{ matrix.drawio }}
          build-args:
            VCS_REF=${{ github.ref }}
            VERSION=${{ env.VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          context: ${{ matrix.drawio }}/
          file: ${{ matrix.drawio }}/Dockerfile
          platforms: linux/amd64
          load: True
      
      - name: Test webapp
        run: |
          docker run --name 'drawio' -d ${{ env.IMAGE }}:${{ env.VERSION }}-${{ matrix.drawio }}
          sleep 10
          docker exec drawio /bin/bash -c "curl -i http://localhost:8080"

      - name: Push image
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}-${{ matrix.drawio }},${{ env.IMAGE }}:${{ matrix.drawio }}
          context: ${{ matrix.drawio }}/
          file: ${{ matrix.drawio }}/Dockerfile
          platforms: linux/amd64
          push: True
